# base
# feats_dir: feats/MSRVTT/uniform_frame
feats_dir: feats/MSRVTT/uniform_batch_0.1
model: tsn
decoder: transformer
# transformer_encoder: True
res_box: True

warmup: 10
learning_rate: 0.0001
batch_size: 16
epochs: 100
eval_start: 70
dim_hidden: 512
